### ISSUE TITLE
CJSX splats not handling newlines consistently

### ISSUE THREAD

**Issue by stwr667** [jsdf/coffee-react#19]
Hey James,

We're not on your latest version, so this could be already fixed. Just wanted to give you a heads up of this bug we just worked around today. See screenshots.

![image](https://cloud.githubusercontent.com/assets/1773072/6701949/ab7518fa-cd5e-11e4-9ee0-32df00c82e5a.png)

![image](https://cloud.githubusercontent.com/assets/1773072/6701960/cdb45502-cd5e-11e4-9d93-2136d43b895a.png)

**Comment by jsdf** [comment]
I think that's the same as https://github.com/jsdf/coffee-react-transform/issues/46

**Comment by stwr667** [comment]
yep, spot on. Thanks for fixing that @jsdf ! Just like having you here, haha :D

**Comment by jsdf** [comment]
No worries
