### ISSUE TITLE
Dependencies are out of date

### ISSUE THREAD

**Issue by jez** [jsdf/coffee-react#28]
Looks like Facebook deprecated JSTransform and react-tools in June. It's being replaced by Babel, which is probably for the better.

https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html

**Comment by jsdf** [comment]
I'm not sure pulling babel in as a dependency is ideal, because all that we're using from react-tools is the displayname transform :\

**Comment by jez** [comment]
I was just doing some ~~spring~~ winter break cleaning of issue's I'm following and I noticed that recently you removed jstransform with coffee-react-transform. I looked at it on npm, but it didn't have any documentation.

Was that done to address this issue? (It's hard to tell without knowing what coffee-react-jstransform is!)

**Comment by jsdf** [comment]
Not much. It's still using jstransform, I've just vendored it into the new package. Literally all it is used for is one tiny syntax transform on the JS output of the Coffeescript compiler (to add in the `displayName` property). The output of the CS compiler hopefully a fairly stable target, as it aims to keep support for some fairly legacy browsers. Until there are actual demonstrable problems with using jstransform I'd rather do that than pull in Babel for this one very small thing.

**Comment by fa7ad** [comment]
may be it will add better error handling? #32
