### ISSUE TITLE
Update CoffeeScript dependency

### ISSUE THREAD

**Issue by ezekg** [jsdf/coffee-react#37]
In order to fix https://github.com/jsdf/coffee-react-transform/issues/66, we should be able to just update the `coffee-script` dependency. The feature to allow interpolations in object keys was added in this commit: https://github.com/jashkenas/coffeescript/commit/76c076db555c9ac7c325c3b285cd74644a9bf0d2.  If I created a PR, how soon could you merge it in and cut a new release? Are there other blockers to updating CS that I'm overlooking?

**Comment by jsdf** [comment]
Unfortunately that won't fix it, code changes need to be made to the coffee-react-transform parser based on the upstream changes in the coffeescript lexer to support this new syntax.

**Comment by ezekg** [comment]
What do you think needs to be done to the parser to add support? I guess I can't find anywhere in the parser that would need to transform object keys. I might try and get my hands dirty if it's not too involved.

**Comment by jsdf** [comment]
Actually it looks like you are right, the coffee-react-transform process should pass this syntax through untouched. In fact, the coffee-react npm package specifies a dependency on coffeescript with a loose dependency constraint of `^1.9.1` which means that all you have to do is `rm -rf` coffee-react and reinstall it, and it should install the latest version of coffeescript.

**Comment by ezekg** [comment]
Could you publish the new version of [grunt-coffee-react](https://github.com/jsdf/grunt-coffee-react)? Current version depends on on [coffee-react `2.4.1`, which has a hard dependency on CoffeeScript `1.8.0`](https://github.com/jsdf/coffee-react/blob/v2.4.1/package.json?ts=2#L40). Thanks!

**Comment by jeffmicklos** [comment]
Same boat here, trying to build a project with `grunt-coffee-react` that has interpolated object keys!

Love all the work you've done so far, @jsdf, thanks for everything!

**Comment by jsdf** [comment]
Published [coffee-react v5.0.0](https://github.com/jsdf/coffee-react/releases/tag/v5.0.0) and [grunt-coffee-react v5.0.0](https://github.com/jsdf/grunt-coffee-react/releases/tag/v5.0.0)

**Comment by jeffmicklos** [comment]
You live up to your name, truly a friend.
