### ISSUE TITLE
Release coffee-react-jstransform

### ISSUE THREAD

**Issue by cia48621793** [jsdf/coffee-react#41]
I am willing to 'maintain' it, I'm a student and so I don't have much time, but right now, we need some little fixes.

The coffee-react-jstransform package is not even public at all, by a little 'reverse engineering' on `dist/js-syntax-transform.js` it seems like it embedded an ESPrima compiler with JSX syntax enabled and some unknown wrapper located at the bottom of the script.

[CoffeeScript is not dead](http://coffeescript.org/v2/#top). The contributors are doing very hard to keep the pace of CoffeeScript up to date. Hopefully, we can also keep CJSX alive, even it was abandoned, we should have picked up the ashes, such good infrastructure should not be made to waste.

**Comment by jsdf** [comment]
sure, here it is: https://github.com/jsdf/coffee-react-jstransform

**Comment by cia48621793** [comment]
＠jsdf is that facebookarchive/jstransform not esprima? oh i misunderstood it...
