### ISSUE TITLE
Enable 'cjsx -w <directory>'

### ISSUE THREAD

**Issue by tugend** [jsdf/coffee-react#8]
The script does not support watch on directories, which is a shame.

**Comment by aleclarson** [comment]
`cjsx -cw ./*.csjx` gives me the message `File not found: path/to/dir/*.cjsx`

How am I expected to match all `.csjx` files nowadays?

**Comment by jsdf** [comment]
What platform are you on (Mac/Windows/Linux)?

**Comment by aleclarson** [comment]
It's no longer an issue, thanks though!
